{
 "title": "Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "pg_database_size_bytes{datname=\"arch\"}",
     "legendFormat": "Size, mb"
    }
   ]
  },
  {
   "title": "TIMES DISK BLOCKS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "irate(pg_stat_database_blks_hit{datname=\"arch\"}[1m])",
     "legendFormat": "blks hit"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\"arch-homework.*\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "MEMORY",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~\"arch-homework.*\", container!=\"\", image!=\"\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Nginx", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum by (exported_namespace) (rate(nginx_ingress_controller_request_duration_seconds_count[1m]))",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "LATENCY",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket[1m]))) * 1000",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket[1m]))) * 1000",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket[1m]))) * 1000",
     "legendFormat": "0.99"
    },
    {
     "expr": "histogram_quantile(1, sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket[1m]))) * 1000",
     "legendFormat": "1"
    }
   ]
  },
  {
   "title": "ERROR RATE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
   "targets": [
    {
     "expr": "sum by (status) (increase(nginx_ingress_controller_request_duration_seconds_count{status=~\"5.+\"}[1m]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  { "title": "User Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by (method) (rate(app_request_count{exported_endpoint=~\".*/user.*\"}[1m]))",
     "legendFormat": "{{method}} /v1/user/*"
    },
    {
     "expr": "sum by (method, exported_endpoint) (irate(app_request_latency_seconds_count{exported_endpoint!~\".*/user.*\"}[1m]))",
     "legendFormat": "{{method}} {{exported_endpoint}}"
    }
   ]
  },
  {
   "title": "ERROR RATE",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum by (method) (increase(app_request_latency_seconds_count{exported_endpoint=~\".*/user.*\",http_status=~\"5.+\"}[1m]))",
     "legendFormat": "{{method}} /user/*"
    },
    {
     "expr": "sum by (method, exported_endpoint) (increase(app_request_latency_seconds_count{exported_endpoint!~\".*/user.*\", http_status=~\"5.+\"}[1m]))",
     "legendFormat": "{{method}} {{exported_endpoint}}"
    }
   ]
  },
  {
   "title": "LATENCY 0.5",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, \n      sum by (le, method) \n         (rate(app_request_latency_seconds_bucket{exported_endpoint!=\".*/user.*\"}[1m]))\n) * 1000",
     "legendFormat": "{{method}} v1/user/*"
    },
    {
     "expr": "histogram_quantile(0.5, \n      sum by (le, method, exported_endpoint) \n         (rate(app_request_latency_seconds_bucket{exported_endpoint!~\".*/user.*\"}[1m]))\n) * 1000",
     "legendFormat": "{{method}} {{exported_endpoint}}"
    }
   ]
  },
  {
   "title": "LATENCY 0.95",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 33 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, \n      sum by (le, method) \n         (rate(app_request_latency_seconds_bucket{exported_endpoint!=\".*/user.*\"}[1m]))\n) * 1000",
     "legendFormat": "{{method}} v1/user/*"
    },
    {
     "expr": "histogram_quantile(0.95, \n      sum by (le, method, exported_endpoint) \n         (rate(app_request_latency_seconds_bucket{exported_endpoint!~\".*/user.*\"}[1m]))\n) * 1000",
     "legendFormat": "{{method}} {{exported_endpoint}}"
    }
   ]
  },
  {
   "title": "LATENCY 0.99",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \n      sum by (le, method) \n         (rate(app_request_latency_seconds_bucket{exported_endpoint!=\".*/user.*\"}[1m]))\n) * 1000",
     "legendFormat": "{{method}} v1/user/*"
    },
    {
     "expr": "histogram_quantile(0.99, \n      sum by (le, method, exported_endpoint) \n         (rate(app_request_latency_seconds_bucket{exported_endpoint!~\".*/user.*\"}[1m]))\n) * 1000",
     "legendFormat": "{{method}} {{exported_endpoint}}"
    }
   ]
  },
  {
   "title": "LATENCY MAX",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 33 },
   "targets": [
    {
     "expr": "histogram_quantile(1, \n      sum by (le, method) \n         (rate(app_request_latency_seconds_bucket{exported_endpoint!=\".*/user.*\"}[1m]))\n) * 1000",
     "legendFormat": "{{method}} v1/user/*"
    },
    {
     "expr": "histogram_quantile(1, \n      sum by (le, method, exported_endpoint) \n         (rate(app_request_latency_seconds_bucket{exported_endpoint!~\".*/user.*\"}[1m]))\n) * 1000",
     "legendFormat": "{{method}} {{exported_endpoint}}"
    }
   ]
  }
 ]
}