apiVersion: v2
name: app
description: A Helm chart for Kubernetes

type: application

version: 0.2.0
appVersion: "v3.3"

dependencies:
  - name: postgresql
    version: 10.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
    tags:
      - app-database
