replicaCount: 3

image:
  repository: getsky/arch.homework

serviceAccount:
  create: true
  annotations: {}

podAnnotations: {}

podSecurityContext: {}
securityContext: {}

service:
  type: NodePort
  port: 80

ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
    - host: arch.homework
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

application:
  port: 8000

postgresql:
  enable: true
  postgresqlUsername: myuser
  postgresqlPassword: arch
  postgresqlDatabase: arch
  service:
    type: LoadBalancer
    port: "5432"