apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" . }}-config
data:
  APP_PORT: {{ .Values.application.port | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}-secret
type: Opaque
data:
  APP_DATABASE_URI: {{ printf "host=%s user=%s password=%s dbname=%s port=%s" (include "postgresql.fullname" .) .Values.postgresql.postgresqlUsername .Values.postgresql.postgresqlPassword .Values.postgresql.postgresqlDatabase .Values.postgresql.service.port   | b64enc | quote }}